### ISSUE TITLE
Camera image is always black

### ISSUE THREAD

**Issue by DevCat-Tom** [pieye/nimbus-images#1]
Hi, i have trouble in taking the camera into operation.
I connected the camera to the Pi as described in the guideline and booted the nimbus_rpi3_rpi4_v0.1.78_d998e541_shrink.img. Using Pi4B and the original power supply.
After connecting via the browser the page is loaded but the camera image is always black.

To dig a bit further i tried to test the camera with python, therefore i installed the following packages:
sudo apt-get install python3-pip
pip3 install nimbus-python
sudo apt-get install libatlas-base-dev  # required to solve: ImportError: libf77blas.so.3

To test the camera i executed the code below on the Pi.
On each execution "cli.getImage(invalidAsNan=True)" throws a TimeoutError.
Is there a way to ensure the camera is working properly and its just a software issue?
If you have any questions feel free to ask.

Code:
~~~
from nimbusPython import NimbusClient
cli = NimbusClient.NimbusClient("localhost")
print("UserlandVersion:", cli.getUserlandVersion())
header, (ampl, radial, x,y,z, conf) = cli.getImage(invalidAsNan=True)
~~~

Code output:
~~~
UserlandVersion: NimbusUserland V0.1.78 | d998e541 | 2020-09-29 08:06:43
The coroutine raised an exception:
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/nimbusPython/NimbusClient.py", line 223, in _pollQueue
    image = await asyncio.wait_for(self._imageQueue.get(), timeout=self._rcvTimeout)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

Traceback (most recent call last):
  File "hellocam_local.py", line 4, in <module>
    header, (ampl, radial, x,y,z, conf) = cli.getImage(invalidAsNan=True)
TypeError: cannot unpack non-iterable NoneType object
~~~
[nimbus-logs.txt](https://github.com/pieye/nimbus-images/files/5723694/nimbus-logs.txt)

**Comment by Coimbra1984** [comment]
Hmm this is strange. The log clearly shows that the imager process is started.
Can you execute the code above from a desktop machine (i.e. not connect through "localhost" but another physical machine).

**Comment by DevCat-Tom** [comment]
Sorry for the late reply. I executed it on a laptop and got the same result.
Don’t get me wrong but I expect this to be a plug&play device, if we can’t get it to work I have no use for it and will send it back. The fact that the camera has no LEDs to signal states makes it harder to figure out if its a software or a hardware problem. All we have are the log files...
Any suggestions?

~~~
from nimbusPython import NimbusClient
cli = NimbusClient.NimbusClient("192.168.0.129")
print("UserlandVersion:", cli.getUserlandVersion())
header, (ampl, radial, x,y,z, conf) = cli.getImage(invalidAsNan=True)
~~~

Code output:
~~~
C:\Users\robin\AppData\Local\Programs\Python\Python37\python.exe C:/Users/robin/Downloads/Nimbus/NimbusTest/NimbusClient.py
The coroutine took too long, cancelling the task...
The coroutine raised an exception:
Traceback (most recent call last):
  File "C:/Users/robin/Downloads/Nimbus/NimbusTest/NimbusClient.py", line 223, in _pollQueue
    image = await asyncio.wait_for(self._imageQueue.get(), timeout=self._rcvTimeout)
  File "C:\Users\robin\AppData\Local\Programs\Python\Python37\lib\asyncio\tasks.py", line 409, in wait_for
    await waiter
concurrent.futures._base.CancelledError

Traceback (most recent call last):
  File "C:/Users/robin/Downloads/Nimbus/NimbusTest/NimbusClient.py", line 460, in <module>
    header, (ampl, radial, x, y, z, conf) = cli.getImage(invalidAsNan=True)
TypeError: cannot unpack non-iterable NoneType object

Process finished with exit code -1
~~~
[nimbus_server_log.g3log.20210104-120143.log](https://github.com/pieye/nimbus-images/files/5764573/nimbus_server_log.g3log.20210104-120143.log)

**Comment by DevCat-Tom** [comment]
I sent it back.
